### ISSUE TITLE
Docker - bridge - Application run failed

### ISSUE THREAD

**Issue by chakjer** [konqi/roborock-bridge#3]
Hi,
For v0.0.5 bridge stop working after announced on mqtt.
Frontend works fine i think so, i see map.
```
bridge_1      | 2024-01-25T20:32:09.334Z  INFO 1 --- [           main] d.k.roborockbridge.bridge.BridgeMqtt     : Announcing 16 rooms.
bridge_1      | 2024-01-25T20:32:09.590Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
bridge_1      | 
bridge_1      | org.springframework.web.client.RestClientException: Error while extracting response for type [de.konqi.roborockbridge.remote.rest.dto.user.UserApiResponseDto<java.util.List<? extends de.konqi.roborockbridge.remote.rest.dto.user.UserScenes>>] and content type [application/json]
bridge_1      | 	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:118) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1132) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1115) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:865) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:785) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:685) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	at de.konqi.roborockbridge.remote.rest.UserApi.getCleanupScenes(UserApi.kt:92) ~[classes!/:0.0.5-SNAPSHOT]
bridge_1      | 	at de.konqi.roborockbridge.BridgeService.init(BridgeService.kt:80) ~[classes!/:0.0.5-SNAPSHOT]
bridge_1      | 	at de.konqi.roborockbridge.BridgeService.worker(BridgeService.kt:116) ~[classes!/:0.0.5-SNAPSHOT]
bridge_1      | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
bridge_1      | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
bridge_1      | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
bridge_1      | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
bridge_1      | 	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:348) ~[spring-context-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:233) ~[spring-context-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:165) ~[spring-context-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174) ~[spring-context-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445) ~[spring-context-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109) ~[spring-boot-3.1.5.jar!/:3.1.5]
bridge_1      | 	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80) ~[spring-boot-3.1.5.jar!/:3.1.5]
bridge_1      | 	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
bridge_1      | 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118) ~[spring-boot-3.1.5.jar!/:3.1.5]
bridge_1      | 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112) ~[spring-boot-3.1.5.jar!/:3.1.5]
bridge_1      | 	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80) ~[spring-boot-3.1.5.jar!/:3.1.5]
bridge_1      | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.1.5.jar!/:3.1.5]
bridge_1      | 	at de.konqi.roborockbridge.RoborockBridgeApplicationKt.main(RoborockBridgeApplication.kt:38) ~[classes!/:0.0.5-SNAPSHOT]
bridge_1      | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
bridge_1      | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
bridge_1      | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
bridge_1      | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
bridge_1      | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[roborock-bridge-0.0.5-SNAPSHOT.jar:0.0.5-SNAPSHOT]
bridge_1      | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[roborock-bridge-0.0.5-SNAPSHOT.jar:0.0.5-SNAPSHOT]
bridge_1      | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[roborock-bridge-0.0.5-SNAPSHOT.jar:0.0.5-SNAPSHOT]
bridge_1      | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[roborock-bridge-0.0.5-SNAPSHOT.jar:0.0.5-SNAPSHOT]
bridge_1      | Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
bridge_1      |  at [Source: (String)"{"triggers":[{"name":"TIMER","type":"TIMER","entityId":"TIMER","param":"{\"cron\": \"6 20 * * 0,1,2,3,4,5,6\", \"enabled\": true, \"repeated\": true, \"timeZoneId\": \"Europe/Warsaw\"}"}],"action":{"type":"S","items":[{"id":1,"type":"CMD","name":"Korytarz","entityId":"7h2sLZVVs3oeb2JXEJSHP3","param":"{\"id\":1,\"method\":\"do_scenes_segments\",\"params\":{\"data\":[{\"tid\":\"1697821693196\",\"segs\":[{\"sid\":16}],\"map_flag\":0,\"fan_power\":102,\"water_box_mode\":202,\"mop_mode\":300,\"mop_te"[truncated 114 chars]; line: 1, column: 14] (through reference chain: de.konqi.roborockbridge.remote.rest.dto.user.UserSceneParam["triggers"]->java.util.ArrayList[0])
bridge_1      | 	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:406) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:354) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:103) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	... 36 common frames omitted
bridge_1      | Caused by: com.fasterxml.jackson.databind.JsonMappingException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
bridge_1      |  at [Source: (String)"{"triggers":[{"name":"TIMER","type":"TIMER","entityId":"TIMER","param":"{\"cron\": \"6 20 * * 0,1,2,3,4,5,6\", \"enabled\": true, \"repeated\": true, \"timeZoneId\": \"Europe/Warsaw\"}"}],"action":{"type":"S","items":[{"id":1,"type":"CMD","name":"Korytarz","entityId":"7h2sLZVVs3oeb2JXEJSHP3","param":"{\"id\":1,\"method\":\"do_scenes_segments\",\"params\":{\"data\":[{\"tid\":\"1697821693196\",\"segs\":[{\"sid\":16}],\"map_flag\":0,\"fan_power\":102,\"water_box_mode\":202,\"mop_mode\":300,\"mop_te"[truncated 114 chars]; line: 1, column: 14] (through reference chain: de.konqi.roborockbridge.remote.rest.dto.user.UserSceneParam["triggers"]->java.util.ArrayList[0]) (through reference chain: de.konqi.roborockbridge.remote.rest.dto.user.UserApiResponseDto["result"]->java.util.ArrayList[1]->de.konqi.roborockbridge.remote.rest.dto.user.UserScenes["param"])
bridge_1      | 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1853) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:572) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:395) ~[spring-web-6.0.13.jar!/:6.0.13]
bridge_1      | 	... 38 common frames omitted
bridge_1      | Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
bridge_1      |  at [Source: (String)"{"triggers":[{"name":"TIMER","type":"TIMER","entityId":"TIMER","param":"{\"cron\": \"6 20 * * 0,1,2,3,4,5,6\", \"enabled\": true, \"repeated\": true, \"timeZoneId\": \"Europe/Warsaw\"}"}],"action":{"type":"S","items":[{"id":1,"type":"CMD","name":"Korytarz","entityId":"7h2sLZVVs3oeb2JXEJSHP3","param":"{\"id\":1,\"method\":\"do_scenes_segments\",\"params\":{\"data\":[{\"tid\":\"1697821693196\",\"segs\":[{\"sid\":16}],\"map_flag\":0,\"fan_power\":102,\"water_box_mode\":202,\"mop_mode\":300,\"mop_te"[truncated 114 chars]; line: 1, column: 14] (through reference chain: de.konqi.roborockbridge.remote.rest.dto.user.UserSceneParam["triggers"]->java.util.ArrayList[0])
bridge_1      | 	at de.konqi.roborockbridge.utility.NestedJsonDeserializer.convert(NestedJsonDeserializer.kt:13) ~[classes!/:0.0.5-SNAPSHOT]
bridge_1      | 	at de.konqi.roborockbridge.utility.NestedJsonDeserializer.convert(NestedJsonDeserializer.kt:8) ~[classes!/:0.0.5-SNAPSHOT]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.convertValue(StdDelegatingDeserializer.java:337) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer.deserialize(StdDelegatingDeserializer.java:174) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	... 55 common frames omitted
bridge_1      | Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
bridge_1      |  at [Source: (String)"{"triggers":[{"name":"TIMER","type":"TIMER","entityId":"TIMER","param":"{\"cron\": \"6 20 * * 0,1,2,3,4,5,6\", \"enabled\": true, \"repeated\": true, \"timeZoneId\": \"Europe/Warsaw\"}"}],"action":{"type":"S","items":[{"id":1,"type":"CMD","name":"Korytarz","entityId":"7h2sLZVVs3oeb2JXEJSHP3","param":"{\"id\":1,\"method\":\"do_scenes_segments\",\"params\":{\"data\":[{\"tid\":\"1697821693196\",\"segs\":[{\"sid\":16}],\"map_flag\":0,\"fan_power\":102,\"water_box_mode\":202,\"mop_mode\":300,\"mop_te"[truncated 114 chars]; line: 1, column: 14] (through reference chain: de.konqi.roborockbridge.remote.rest.dto.user.UserSceneParam["triggers"]->java.util.ArrayList[0])
bridge_1      | 	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1431) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:943) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1424) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:218) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:184) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:27) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1409) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740) ~[jackson-databind-2.15.3.jar!/:2.15.3]
bridge_1      | 	at de.konqi.roborockbridge.utility.NestedJsonDeserializer.convert(NestedJsonDeserializer.kt:11) ~[classes!/:0.0.5-SNAPSHOT]
bridge_1      | 	... 60 common frames omitted
bridge_1      | 
bridge_1      | 2024-01-25T20:32:09.620Z  INFO 1 --- [           main] de.konqi.roborockbridge.BridgeService    : Shutting down bridge service
bridge_1      | 2024-01-25T20:32:09.633Z  WARN 1 --- [           main] .s.c.a.CommonAnnotationBeanPostProcessor : Destroy method on bean with name 'roborockMqtt' threw an exception: kotlin.UninitializedPropertyAccessException: lateinit property mqttClient has not been initialized
bridge_1      | 2024-01-25T20:32:09.656Z  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
bridge_1      | 2024-01-25T20:32:09.661Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
bridge_1      | 2024-01-25T20:32:09.667Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
roborock-bridge-005_bridge_1 exited with code 1
```

**Comment by konqi** [comment]
I see, looks like you have a scheduled cleanup configured. That's something I don't use. I'll have a look.

**Comment by konqi** [comment]
I made a small change. Should be possible to parse triggers now.
